### ISSUE TITLE
How do you use it ?

### ISSUE THREAD

**Issue by GuckicheLorraine** [fnr1r/kadishutu#2]
Hello ! How do I use it ? I've installed pipx but it Kadishutu save editor doesn't seem to be a package so how can I install it using pipx ?
I've also cloned the repo but it doesn't seem to have a built script.

**Comment by ukiyo-dev** [comment]
Use `pipx install git+https://github.com/fnr1r/kadishutu.git` command.

**Comment by fnr1r** [comment]
You can also run `pipx install /path/to/kadishutu`, it should work too.

**Comment by GuckicheLorraine** [comment]
It worked like a charm. Sorrt for the inconvenience, it was my first time installing an app this way and I had trouble googling the solution.
Thank you very much !
